0:
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA9DQMM-if00-port0
  config:
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_signs: [1, 1, -1, 1, 1, 1]
    joint_offsets: [3.141592653589793, 3.141592653589793, 3.141592653589793, 3.141592653589793, 3.141592653589793, 4.71238898038469]
    gripper_config: [7, 200.36640625, 158.56640625]